### ISSUE TITLE
sci-mathematics/acl2-8.4 fails to compile with `books` or `doc` USE flag enabled

### ISSUE THREAD

**Issue by lucasmitrak** [gentoo/sci#1113]
sci-mathematics/acl2 was version bumped during a bug fix PR [1]. However, it seems version 8.3 and 8.4 are too different for the ebuild to be version bumped so easily. Even without these flags, the package does not compile correctly. Therefore, I suggest the original PR is implemented with the original version 8.3. If a version bump is desired, I suggest creating a bug report. Logs are attached.

[1] https://github.com/gentoo/sci/pull/1109
[logs.zip](https://github.com/gentoo/sci/files/7189400/logs.zip)

**Comment by AndrewAmmerlaan** [comment]
Sorry, I can't seem to find the full build log in this zip file, could you attach it please?

Version 8.4 compiled successfully for me before, so I doubt the problem is the version bump. Maybe some incompatibility with a dependency was introduced by some version bump somewhere else? 
[acl2-8.4:20210912-073000.log](https://github.com/gentoo/sci/files/7189494/acl2-8.4.20210912-073000.log)

I'll test again and see if I can reproduce this.

**Comment by lucasmitrak** [comment]
[logs.zip](https://github.com/gentoo/sci/files/7190522/logs.zip)
This zip includes the build log. This was done inside an isolated docker image using ebuildtester. I cannot think of why we are getting a different result. I think I will try installing outside of the docker image to see if it makes a difference; I will look into this later.

**Comment by lucasmitrak** [comment]
@AndrewAmmerlaan  You are running sbcl version 2.1.8 according to the log file you uploaded which states "This is SBCL 2.1.8". acl2-8.4 requires a sbcl version greater then 1.5.2. The unmasked version is 1.4.9 and the next version after that is 2.1.5. So I will create a PR which adds requests a sbcl version greater then or equal to 1.5.2 and put all my evidence of this requirement there.
