### ISSUE TITLE
pytorch: cuda support

### ISSUE THREAD

**Issue by Miezhiko** [gentoo/sci#1141]
based on: https://github.com/gentoo/sci/pull/1132

seems like it's not possible to build `pytorch` with `cuda` flag because of `clhpp-2`

**Comment by TheChymera** [comment]
@Miezhiko yes, I've been struggling with this for a while as well, and in fact it's holding one of our projects back. I remember @Jimmy2027 had figured out how to make it work using this overlay: https://github.com/aclex/pytorch-ebuild

My problem is I don't really use it for any other projects, and I don't even have dedicated GPUs on any system except the one I co-admin with Hendrik, so I think it might be better if someone who actually uses it regularly can figure it out. Can't really maintain it myself not using the respective hardware :(

**Comment by Miezhiko** [comment]
@TheChymera 
Thank you, at first I see the major difference in ebuilds there with `USE_NCCL=OFF` being forced there.
And I will try that.

**Comment by AndrewAmmerlaan** [comment]
> I remember @Jimmy2027 had figured out how to make it work using this overlay: https://github.com/aclex/pytorch-ebuild

Wait a minute, there is an actively maintained dedicated overlay for this package? Then why do we package it in `::sci` as well? Shouldn't we avoid the double work and either merge that overlay into `::sci` or remove the package from `::sci`?

**Comment by Miezhiko** [comment]
that overlay is not even on gpo, hard to find, ebuild itself looks more clear with 3rd parties, but now I'm not sure if it's better on everything. I will possibly try different combinations.

**Comment by Miezhiko** [comment]
the thing is ... his ebuild fails with absolutely same error with cuda USE flag :'(

**Comment by TheChymera** [comment]
> Wait a minute, there is an actively maintained dedicated overlay for this package? Then why do we package it in `::sci` as well?

Alexey Chernov is the author of both and even references the overlay in his https://gitweb.gentoo.org/proj/sci.git/commit/?id=bb46b0f6b4260c8aca367dc153b10a385d9728eb commit.

But the main reason why it would make sense to try and have it here would be if we could help him do it better, since the version from the overlay doesn't work particularly well. Maybe we can ping @aclex and see whether he would like to relocate the main effort here here since I assume he has push access, and ::science would help make his ebuild more accessible, and we might more easily help him in some meaningful way.

**Comment by aclex** [comment]
Hi, thanks for the interest in my project! As for the CUDA issue, I'm afraid, I can't help too much here as I also don't have NVIDIA hardware to test it thoroughly, just added some basic support initially and accepted contributions of @Jimmy2027 who seemed to manage to get it work on NVIDIA previously.

As for joining efforts, I'm generally fully for it, but as the result of the discussion a couple of years ago (https://github.com/gentoo/sci/pull/941) we came to that only some selected parts of the ebuilds might be merged in sci, due to lower code quality in my project and other issues, so we decided to maintain both versions separately. Still I'm open for any co-operation with this.

**Comment by AndrewAmmerlaan** [comment]
> As for joining efforts, I'm generally fully for it, but as the result of the discussion a couple of years ago (#941) we came to that only some selected parts of the ebuilds might be merged in sci, due to lower code quality in my project and other issues, so we decided to maintain both versions separately. Still I'm open for any co-operation with this.

I think the ebuild quality is mostly fine (we have way worse stuff in this repository anyway :P ).

After a quick glance through the ebuilds in your repository I have only a few comments:

1)
```
src_unpack() {
	unpack ${A}
	mv "${WORKDIR}/${P//torch/}" "${S}"
}
``` 
Instead of this just set `S="${WORKDIR}/${P//torch/}"`.

2)

Don't use the `-f` argument for `rm`, with that argument `|| die` doesn't do anything any more since the exit status will always be success.

3) 

Explicit dependency on setuptools can be dropped from the python ebuilds, this is controlled by the eclass

4) 

Don't inherit `git-r3` eclass in non-live ebuilds, this overrides the Manifest checks (and is prone to break anyway). Use snapshot tarballs in `SRC_URI` instead.

IMO it would be great if we can merge these efforts and avoid double work. We can take the best of both versions and hopefully arrive at an even better ebuild.

**Comment by aclex** [comment]
@AndrewAmmerlaan many thanks for the quick review and comments — will fix and test them tonight. (4) is probably most difficult due to the number of submodules and changes there, but I also tend to like the proposed approach instead of `git-r3`.

Yes, indeed, duplicate code rarely helps)

**Comment by TheChymera** [comment]
Perhaps we should also ping @heroxbd since he previously showed interest in this. I also notice @aclex 's commit was signed off by him. Do you not have push access to ::science ? If so, it would be a good idea to request it in #gentoo-science on IRC. I think that would help you more easily migrate development work to here. Ofc for rough drafts best test them locally first, and always check `repoman full` before committing :)

**Comment by heroxbd** [comment]
I am following the discussions. Thank you guys.

It would be the best if we can have a PR for `cuda` fix :)

**Comment by heroxbd** [comment]
FYI: PyTorch 1.10 has almost rewritten its `cuda` and `ROCm` kernel launchers.

**Comment by aclex** [comment]
@TheChymera No, I don't have push access to ::science, but, I think that's no absolute need, I can just send PR on the update here, provided it would be reviewed by someone. As for stability of the changes, yes, try to always follow this way myself already, though some inconsistencies still slip to commits sometimes)

**Comment by mgorny** [comment]
Closing all the remaining bugs since we are removing issue reporting from the GitHub repository. If this issue still applies and it is not reported to [Gentoo Bugzilla](https://bugs.gentoo.org), please file it there.
