### ISSUE TITLE
=sci-physics/openmodelica-9999

### ISSUE THREAD

**Issue by pajot** [gentoo/sci#410]
I have a first, working attempt at a 9999 ebuild for OpenModelica (https://www.openmodelica.org/). It builds the most important components but still has a couple of issues (specifically, the OMoptim doesn't work and has no maintainer upstream, and python interface won't build). Is there any interest in including this in the science overlay?

**Comment by marbre** [comment]
Sure, just send a pull request.

**Comment by vince-ice** [comment]
Hello all, 
anything happened in the meantime?

**Comment by pajot** [comment]
Hi,

I haven't worked on this in a good long while, but I'm willing to take another look at it. I assume my ebuild no longer works.

But this really should be in the science-overlay.

**Comment by vince-ice** [comment]
Hello Stephen,
I definitely agree. I am also interested in working on it in my spare time.
I'll keep you posted on my progresses (if any).
Best,
Vince

Il giorno mer 12 set 2018 alle ore 11:04 Stephen Bosch <
notifications@github.com> ha scritto:

**Comment by vince-ice** [comment]
Dear Stephen,
Could you please provide me with your old ebuild file?
Thanks,
vince

**Comment by vince-ice** [comment]
Dear all,
this is my ebuild for openmodelica-1.13.2. 
I'm not issuing a pull request because I'm not a developer and making an ebuild from scratch was already a difficult task for me.
Anyway, it works well. I hope you guys could refine it, remove errors, and eventually add it to the repo.
The ebuilds downloads sources from git, as that is the only way to download sources from OpenModelica.
I also prepared 2 patches, by looking at the master branch of OpenModelica.
This is my package.use file: 
`sci-physics/openmodelica clang cppruntime -hdf5 -hwloc om_all om_optim om_shellterminal sundials -test doc`
Hope this helps.
My best,
vince

[openmodelica-1.13.2.ebuild.txt](https://github.com/gentoo/sci/files/3560503/openmodelica-1.13.2.ebuild.txt)
[paradiseo-cmake.patch.txt](https://github.com/gentoo/sci/files/3560509/paradiseo-cmake.patch.txt)
[sundials-cmake.patch.txt](https://github.com/gentoo/sci/files/3560510/sundials-cmake.patch.txt)

**Comment by TheChymera** [comment]
please consider making a PR, it would help us better review it and help you get it merged! :)

**Comment by TheChymera** [comment]
@vince-ice as mentioned before, please feel free to submit a PR :)
