### ISSUE TITLE
Version bump: sci-mathematics/scilab-6.0.0

### ISSUE THREAD

**Issue by fusion809** [gentoo/sci#774]
Hi,

Scilab 6.0.0 is out (and has been since 17 February 2017, if you're wondering whether this is some 0th-day update request :P) and I was wondering if there's any intention to bump `sci-mathematics/scilab` to 6.0.0. I know it'd be difficult as for me the scilab-6.0.0 binary tarball falls to launch on Gentoo due to Java issues. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Here's the exact error I get with the Scilab 6.0.0 binary tarball:

```bash
Cannot find this look and feel:
[GTK look and feel - com.sun.java.swing.plaf.gtk.GTKLookAndFeel] not supported on this platform
bin/scilab: line 957:  7894 Segmentation fault      (core dumped) "$SCILABBIN" "$@"
```

**Comment by kiwifb** [comment]
Using `icedtea{,-bin}` or `sun-j{re,dk}`? If `icedtea` do you have the `gtk` useflag enabled?

**Comment by fusion809** [comment]
`dev-java/icedtea-bin` with GTK USE enabled is what I have.

**Comment by kiwifb** [comment]
Hum, may need to emerge `swingx-ws`. I am in unchartered territory here but I am guessing you need to install more stuff since it appears there is no `swing` components in the shipped `icedtea-bin:8`.

**Comment by fusion809** [comment]
Tried emerging `swingx-ws` still fails to launch with the same error.

**Comment by eolianoe** [comment]
Sorry to hijack the thread, but did you find any solution to your problem?

**Comment by fusion809** [comment]
Afraid not. Seems quite insane that Gentoo, one of the most customizable distros, has trouble running such a simple, cross-distro binary.

**Comment by eolianoe** [comment]
If it can help you, I'm getting the same error on an Arch box whereas there is no error when building from source.

**Comment by scivision** [comment]
Any updates on this? I still get the same 

    Cannot find this look and feel:
    [GTK look and feel - com.sun.java.swing.plaf.gtk.GTKLookAndFeel] not supported on this platform
    Segmentation fault (core dumped)

**Comment by jborme** [comment]
On gentoo: same problem with oracle-jdk-bin, icedtea-bin, and also with jdk-with-com-sun installed. Other distros are affected as well (Manjaro, Arch, Mageia)

Upstream bug: http://bugzilla.scilab.org/show_bug.cgi?id=15145

Right now there is no way to run scilab out-of-the-box on gentoo. 
* scilab-5.5.2-r1 will not build due to missing dependency
* binary scilab (both 5.5 and 6.0) segfault

To build scilab-5.5.2-r1, one must recover batik-1.8-r2 ebuild from https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-java/batik/ Then scilab-5.5.2-r1 builds.

Note that this bug due to some change in gentoo (or other distros) after scilab 6 was out. In the early 2017, scilab 5 and 6 from the binaries were working.

**Comment by jborme** [comment]
Upstream suggested: _JAVA_OPTIONS='-Dswing.installedlafs=com.sun.java.swing.plaf.gtk.GTKLookAndFeel' /path/to/bin/scilab

This workaround works for scilab-5.5.1 binary (which then appears with Metal look and feel), but not for scilab-6.0.0 binary.

The result is same with or without swing-ws, swingx-ws packages, and with icedtea-bin-3.6.0 or oracle-jdk-bin-1.8.0.152-r1 (8u152)
