### ISSUE TITLE
dev-cpp/eigen-3.3.3 version bump

### ISSUE THREAD

**Issue by devurandom** [gentoo/sci#799]
It would be nice if Eigen could be bumped to 3.3, to bring it more in sync with the main Gentoo repository.

Eventually it would be great, if Science Overlay's Eigen could be merged back into Gentoo. That would help with a lot of dependency conflicts I usually need to sort out manually.

**Comment by kiwifb** [comment]
I just looked at eigen 3.3 a little bit. I think there are still the bits to build blas, although it is not in the main documentation I have seen. What I have seen is that you can use a system blas/lapack in eigen. So there are 3 states possibles:
* plain not using blas/lapack and not providing it.
* providing blas
* using system blas/lapack
I don't think the last two are actually mutually exclusive technically (but sanity probably requires it).
Which states should we support?

**Comment by devurandom** [comment]
if possible, all three? You could set `IUSE='blas system-blas'` and `REQUIRED_USE='blas? ( !system-blas ) system-blas? ( !blas )'`. `virtual/blas` would have to be adjusted accordingly (`RDEPEND='|| ( dev-cpp/eigen[blas] )'`). I'd suggest to start with the `USE=blas` case, since you already had that in previous versions.

**Comment by kiwifb** [comment]
A bit like gsl (which has cblas-external), why not. I like the useflag `blas` but that means changing the current flags which is `fortran` (and which is clearly not obvious, changing it would be an improvement).

**Comment by devurandom** [comment]
In hindsight: My suggestion for `system-blas` is not ideal. It is usually used to switch between bundled and system libraries, which is not what it would mean here. Logically it should probably be `IUSE=blas`, i.e. "I will use BLAS", and `IUSE=blas-provider`, which would mean "I provide BLAS"?

**Comment by kiwifb** [comment]
Hum... yes. `blas` for building against blas is more consistent with the other use of the flag. `bls-provider`? Why not, most thing will be better than `fortran`.

**Comment by kiwifb** [comment]
OK now that I have started working in earnest on this, I see things more clearly. I will keep the useflag `blas-provider` I think, because it is appropriate. 
Outside of blas and lapack (I haven't tested lapack, I'll stick to blas as in 3.2 to start with), eigen doesn't produce any libraries. It just installs headers.
When you use eigen and you put `-DEIGEN_USE_BLAS` or `-DEIGEN_USE_LAPACKE` in your flags you can use an external blas/lapack from eigen. Bring your own library flags as well. It all happen at runtime when someone uses the eigen headers. The only thing we could do is change `eigen.pc` to force usage of blas/lapacke. I don't really believe in that. It also only affects a limited subset of what is provided by eigen, so you impose a high cost for a little change overall.

I think we should stick to the freedom provided by upstream.

**Comment by kiwifb** [comment]
I just had a go at lapack. I don't think it is anywhere near the full implementation so not a viable alternative. Plus it would be difficult to untie it from eigen_blas. I will put a draft PR for review shortly.

**Comment by kiwifb** [comment]
See PR #801. Something appears to be off with my git history. I may have to restart my fork from scratch at some point. I must have accidentally branched from #800 rather than master.

**Comment by devurandom** [comment]
> I think we should stick to the freedom provided by upstream.

Sounds fine. :)

**Comment by marbre** [comment]
Eigen 3.3.7 is available in the main tree, closing this issue therefore.
