### ISSUE TITLE
sci-geosciences/grass::gentoo fails to build with sci-libs/cblas-reference::science

### ISSUE THREAD

**Issue by devurandom** [gentoo/sci#856]
When trying to build sci-geosciences/grass::gentoo with sci-libs/cblas-reference::science, `configure` will fail to find the BLAS library.

[build.log](https://github.com/gentoo/sci/files/1836645/build.log)
[config.log](https://github.com/gentoo/sci/files/1836646/config.log)

I already tried to pass the correct include and library paths to configure (devurandom/gentoo-overlay@1503e88351024b61906bae53766dd0006be8e9e9), but that was only partly successful. Ultimately, [`configure` will try to link against `libblas.so`](https://trac.osgeo.org/grass/browser/grass/tags/release_20180126_grass_7_4_0/configure.in#L1439), which does not exist in the science-overlay way of selecting the C/BLAS implementation.

What is your suggestion how to fix this?

**Comment by kiwifb** [comment]
Depends but the configure script seems to be broken in some ways if it is supposed to be able to take blas/lapack options. I'll have a look.

**Comment by kiwifb** [comment]
`configure.in` (shudder) looks for specific blas implementation (ATLAS,OS X vectorize...) before falling back to a generic case called with `-lblas`. Overall the configure script is beurk. Trying to find where the blas stuff ends up and so on, I have a feeling that you should pass `pkg-config --libs` (i.e. all linking flags not just the libraries or just the folders) to the `--with-blas-libs` option. Same with lapack.
This is because you have a `BLASLIB` variable and that the only thing used in any makefile to link, so your library name has to land there somehow.

At this stage I just patch `configure.in` with something sensible using pkg-config could be envisaged.

**Comment by TheChymera** [comment]
@devurandom cblas-reference does no longer have a `::science`-specific version. Does grass work with the `::gentoo` version? If not, we would either need to update the package, or drop it entirely. If we go for updating, it might make sense to add a static version. Let me know if you would be interested in doing that and would need any help :)

**Comment by devurandom** [comment]
I tried sci-geosciences/grass from `::gentoo` and it requires `USE=eselect-ldso` on the blas-related virtuals, so I stopped. On the other hand I finally managed to emerge sci-geosciences/qgis (without `USE=grass`), which was my actual goal. So I will give up on this for now and close this issue. Feel free to reopen if you disagree.
