### ISSUE TITLE
dev-lang/path64: DEPENDency on non-existing dev-lang/ekopath

### ISSUE THREAD

**Issue by mmokrejs** [gentoo/sci#915]
Hi @Xarthisius ,
  where is the deemed package?

```
  dependency.unknown
   dev-lang/path64/path64-9999.ebuild: DEPEND: dev-lang/ekopath:*
   dev-lang/path64/path64-9999.ebuild: RDEPEND: dev-lang/ekopath:*
```

```
gentoo/sci $ find ../.. -name \*.ebuild | xargs grep dev-lang/ekopath
../../dev-lang/path64/path64-9999.ebuild:	native? ( || ( dev-lang/ekopath:* dev-lang/path64 ) )
gentoo/sci $ find /usr/portage/ -name \*.ebuild | xargs grep dev-lang/ekopath
/usr/portage/virtual/fortran/fortran-0.ebuild:		dev-lang/ekopath
gentoo/sci $
```

**Comment by Xarthisius** [comment]
Hello Ghost of Chritmas Past! Looking at portage it was removed by this commit: https://github.com/gentoo/gentoo/commit/976c5b5fe9c11bca29c94965665aa6b6e3ade846

Almost a year after I retired... :)

**Comment by mmokrejs** [comment]
So this is probably a dupe of https://github.com/gentoo/sci/issues/909 , I think the portage snapshots fetched are just outdated but no idea how they are prepared.

**Comment by TheChymera** [comment]
@mmokrejs @Xarthisius the dependency is indeed gone going by the line `native? ( || ( dev-lang/ekopath:* dev-lang/path64 ) )` systems which still have path64 from back when ekopath existed, can keep on bootstrapping for that, but new systems can't install it.

Would you like to update the ebuild and perhaps add an unmasked static version? This would really be ideal.

Otherwise I think we should either drop the native USE flag, or drop the package entirely. If there's not enough interest to update it, I actually think it would be best to just drop it, but let me know if it's actually of any use for you so that we can keep it without `native`.

**Comment by TheChymera** [comment]
Since interest popped up over the past 3 months, I have removed the package, as it plainly can't be built de novo. Again, if there is interest in this after all, I'd be happy to bring it back pending a PR for a working ebuild.

https://gitweb.gentoo.org/proj/sci.git/commit/?id=9fdef594e724e77ded817c3a752eaf5969a27312
